version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: db-postgres-aluguel
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - dot.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: